### ISSUE TITLE
FR: Store app (intent) which triggered a certain alarm update

### ISSUE THREAD

**Issue by nitobuendia** [Johboh/hassalarm#30]
I've been facing the issue as in #19. Ignored apps is a good fix. My challenge is to know which app to block. At the moment, the only way to do this is by acting on the moment it's been set up as "next alarm" to ignore it. However, I might not have a chance to check at that moment. I would love to understand for all the history of publishes, which app triggered which.

In short, the request here would be to store and show the app source of the alarm on the "Publish history".

For example, instead of:
`@23-03-25 10:48:17 alarm @: 23-03-26 09:30`

Show something like:
`@23-03-25 10:48:17 alarm @: 23-03-26 09:30 by "com.sec.android.app.clockpackage"`

Alternatively, this information could be shown on click, similar to the popup information when you click on errors.

At the moment, this would be only for information, so we can diagnose the source of the problematic apps to ignore. In the future, we could also change it so you could have a one click to add that app to the `Ignore apps` list.

**Comment by Johboh** [comment]
I will look into it!

**Comment by Johboh** [comment]
@nitobuendia I pushed a version that includes the package name now in the history view. It will take some hours for it to propagate. Please give it a go once you receive the update (1.22).

**Comment by Johboh** [comment]
Forgot to hit publish in Google Play Console! Now the new version is actually published (or rather, sent for review). Will take some hours for it to propagate.

**Comment by nitobuendia** [comment]
Thanks a lot, @Johboh, for woking on this and the quick turnaround.

I was waiting for it to be deployed to test it out and I've just tried the new version.

At the moment, when I go to "Publish History", it [shows empty](https://user-images.githubusercontent.com/16522489/227766616-fce6bbac-1d17-41b3-bcc7-6d359683bccc.jpg) and _immediately_ redirects back to the home view. If I leave it be for some seconds, it automatically closes. The app also crashed a couple of times when accessing Publish History, but I am unable to reproduce consistently. Most times, it simply closes without an error.

I have sent the logs via the Android built-in system:

- Source file: AutoValue_NextAlarmUpdatedJob_Request.Java (NextAlarmUpdaterJob.java 65 > 145 > 237 > 315).
- Source class: com.fjun.hassalarm.AutoValue_NextAlarmUpdaterJob_Request (:25)
- java.lang.NullPointerException Null


Could it be that creatorPackage is null because historically it was not collected and it's making the system crash when calling `return new AutoValue_NextAlarmUpdaterJob_Request(call, triggerTimestamp, creatorPackage);`? I assume supporting `@Nullable` or adding some default value (`unknown`?) when it's null could do the trick to avoid breaking history backwards.

**Comment by Johboh** [comment]
😢 
It was supposed to handle null `creatorPackage`. I will look into it (also, I should migrate to kotlin)

**Comment by Johboh** [comment]
@nitobuendia I pushed a new version now (1.23).

**Comment by nitobuendia** [comment]
@Johboh Thank you! Still crashing but different error. I've tried with a Pixel 5 and a Samsung A53.

Error: `Exception while computing database live data` from RoomOpenHelper. I couldn't see the lines since the Preview is quite limited, but it seems the data structures expected and received are different. I've sent the log data via the system.

**Comment by Johboh** [comment]
That is odd, as I added a migration strategy for the database. I will investigate.

**Comment by Johboh** [comment]
@nitobuendia Is this for 1.23 btw? I cannot seams to find any for that version, only the NPE you saw earlier for 1.22.

**Comment by nitobuendia** [comment]
Yes, 1.23, @Johboh - I've sent another report.

**Comment by nitobuendia** [comment]
Updated to 1.24. The app is no longer crashing, but there's also no history shown. I'll report what I see tomorrow. Thanks!

**Comment by Johboh** [comment]
Yes I have to sacrifice the history in favor for not crashing. Lessons learned to next time I change the Room database structure 😊.

**Comment by nitobuendia** [comment]
I've just checked in the morning and the history data is flowing in again, but I still cannot see the app source. Here's a screenshot in horizontal since I had text wrap issues before. Clicking also does not seem to open a pop up or alike.

![Screenshot_20230327-093812](https://user-images.githubusercontent.com/16522489/227820727-ea22b734-0c49-48ae-8e83-351126b9ec65.jpg)

**Comment by Johboh** [comment]
The app source is only shown if the alarm manager is reporting one. Can you verify by trying to set an alarm in the stock Google clock?
I will also investigate this from the API side of things.

**Comment by Johboh** [comment]
Looks like I broke something while converting to kotlin. Will investigate after work today. Sorry for the inconvenience!

**Comment by Johboh** [comment]
It turns out that starting with Android 13, there is no creator package name in the pending intent provided by the AlarmClockInfo. It works on Android 12L. I will investigate further.

**Comment by Johboh** [comment]
@nitobuendia So it looks like starting with Android 13 / API 33, the creator package is no longer set in the Pending Intent for the alarm clock. Other similar apps have the same issue: https://community.openhab.org/t/alarm-clock-andorid-sends-undef/133718
I couldn't find any mention of this in the Android API 33 change log, so unsure if this is a bug or an intentional change.
This also mean that the Ignore App function in the Hassalarm app is no longer functioning.
I'm still trying to find a workaround for this, but no luck so far.

**Comment by Johboh** [comment]
I created a ticket: https://issuetracker.google.com/issues/275678087

**Comment by riotbib** [comment]
Hi, I don't fully grasp this bug to be honest. Not really experienced with Android.

I think I'm experiencing the same faulty behaviour with [Signal](https://github.com/signalapp/Signal-Android/) when timing messages, see screenshots. But: I cannot ignore Signal with hassalarm for some unknown reason…

<img width="200" alt="Image" src="https://github.com/user-attachments/assets/b2333276-35fe-4519-b5c6-57dfa7bacf72" /> <img width="200" alt="Image" src="https://github.com/user-attachments/assets/c96b09aa-479c-4cc5-9d2c-de84c7b559b5" /> <img width="200" alt="Image" src="https://github.com/user-attachments/assets/3a1491cd-df9e-4b4d-bea5-c099ed2aab28" />

They [want to fix that](https://github.com/signalapp/Signal-Android/issues/14565#issuecomment-3812022624). Do you have input for Signal developers on how to do so? Then I comment there, feel free to do so yourself if you want! Or is it possible within hassalarm?

If you need any more input or logs etc from me, let me know. Thanks a lot for this awesome, helpful app. :)

**Comment by Johboh** [comment]
Hej!
If they are fixing it I guess we can just wait it out.
Another option is to add the package name for [signal to this list](https://github.com/Johboh/hassalarm/blob/master/app/src/main/AndroidManifest.xml#L7), and you should be able to ignore it. I can look into that this weekend.

**Comment by Johboh** [comment]
@riotbib I forgot about this! Have Signal fixed this on their slide?

**Comment by riotbib** [comment]
@Johboh oh didn't see your reply from two weeks ago, sorry! I asked [in a related Signal issue](https://github.com/signalapp/Signal-Android/issues/14565#issuecomment-4065576604).

If you want, I can send a PR adding it the package name to the `<queries>` list. I guess that would be the best option to go easy on Signal dev's and yours time.

**Comment by Johboh** [comment]
@riotbib please do!
